name: push_workflow
on:  
    push:
        branches: 
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
            - release-*
    workflow_dispatch:
    # schedule:
    #     - cron : '0 9 * * *'

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print greetings
              run: echo "Hello world"
            - name: Print Good Bye
              run: |
                echo "This is my push workflow"  
                echo "push workflow executed successfully"
              